<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="CSharpier.MSBuild" Version="1.3.0" />
    <GlobalPackageReference Include="Meziantou.Analyzer" Version="3.0.156" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.400" />
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400" />
    <GlobalPackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" />
    <GlobalPackageReference Include="NetEvolve.Analyzer" Version="0.19.0" />
    <GlobalPackageReference Include="NetEvolve.Defaults" Version="2.8.0" />
    <GlobalPackageReference Include="Roslynator.Analyzers" Version="4.16.0" />
    <GlobalPackageReference Include="Roslynator.Formatting.Analyzers" Version="4.16.0" />
    <GlobalPackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="4.16.0" />
    <GlobalPackageReference Include="Roslynator.CodeFixes" Version="4.16.0" />
    <GlobalPackageReference Include="Roslynator.Refactorings" Version="4.16.0" />
    <GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="10.32.0.713" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
    <PackageVersion Include="NetEvolve.Extensions.TUnit" Version="3.5.348" />
    <PackageVersion Include="TngTech.ArchUnitNET.TUnit" Version="0.13.3" />
    <PackageVersion Include="TUnit" Version="1.65.0" />
    <PackageVersion Include="TUnit.Mocks" Version="1.65.0" />
    <PackageVersion Include="Verify.TUnit" Version="31.28.0" />
  </ItemGroup>
</Project>
