name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dotnet-logging:
        required: true
        type: choice
        default: minimal
        options:
          - quiet
          - minimal
          - normal
          - detailed
          - diagnostic

jobs:
  all:
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/build-dotnet-single.yml@920e82e7e688a3e168f046f1fe7f8d1a426e655d # 2.4.5
    with:
      dotnetLogging: ${{ inputs.dotnet-logging }}
      dotnetVersion: ${{ vars.NE_DOTNET_TARGETFRAMEWORKS }}
      runsOnBuild: windows-latest
      solution: ./Extensions.Hosting.WinForms.slnx
    secrets: inherit
