name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dotnet-logging:
        required: true
        type: choice
        default: minimal
        options:
          - quiet
          - minimal
          - normal
          - detailed
          - diagnostic

jobs:
  all:
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/build-dotnet-single.yml@1654472d2498bd41e01367b68ecf2d01acdc92d8 # 2.4.11
    with:
      dotnetLogging: ${{ inputs.dotnet-logging }}
      dotnetVersion: ${{ vars.NE_DOTNET_TARGETFRAMEWORKS }}
      runsOnBuild: windows-latest
      solution: ./Extensions.Hosting.WinForms.slnx
    secrets: inherit
