name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dotnet-logging:
        required: true
        type: choice
        default: minimal
        options:
          - quiet
          - minimal
          - normal
          - detailed
          - diagnostic

jobs:
  all:
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/build-dotnet-single.yml@28edbb9998d002199a7c146c39592f0a8439ca24 # 2.3.163
    with:
      dotnetLogging: ${{ inputs.dotnet-logging }}
      dotnetVersion: ${{ vars.NE_DOTNET_TARGETFRAMEWORKS }}
      runsOnBuild: windows-latest
      solution: ./Extensions.Hosting.WinForms.slnx
    secrets: inherit
